### ISSUE TITLE
firebase error:  Firebase is not a constructor

### ISSUE THREAD

**Issue by pathak333** [pathak333/curious#1]
var Firebase = require("firebase");
var myFirebaseRef = new Firebase("https://button-demo-56e16.firebaseio.com/buttonstatus/buttonStatus");

myFirebaseRef.on("value", function(snapshot) {
    alert(snapshot.val());  // Alerts "San Francisco"
  });

ERROR COME REGARDING THIS CODE

D:\new_iot>node aaa.js
D:\new_iot\aaa.js:2
var myFirebaseRef = new Firebase("https://button-demo-56e16.firebaseio.com/buttonstatus/buttonStatus");
                    ^

TypeError: Firebase is not a constructor
    at Object.<anonymous> (D:\new_iot\aaa.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

SOMEONE HELP ME

**Comment by pathak333** [comment]
solved
